### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xbfding** [chainreactors/zombie#21]
无法读取gogo输出文件中的爆破目标，其他协议还没测，ssh发现没有读取到。
![image](https://github.com/chainreactors/zombie/assets/62999907/b229147b-9d82-448e-bad2-f4e6c6dde952)
![image](https://github.com/chainreactors/zombie/assets/62999907/8ec4455c-f5de-46f9-9373-94ea803fec29)

**Comment by M09Ic** [comment]
因为gogo没正确识别到指纹。 我确认下指纹识别那部分是否有bug
