### ISSUE TITLE
希望改进的点

### ISSUE THREAD

**Issue by mortal-sec** [chainreactors/zombie#29]
希望可以指定hash字典去爆破，以及爆破时候可以指定域名，也就是domain

**Comment by M09Ic** [comment]
这两点目前都是支持的。

hash爆破请见： https://chainreactors.github.io/wiki/zombie/start/#smb

域名直接使用-i 或者list文件输入即可

**Comment by mortal-sec** [comment]
我看说明好像只可以单个hash，有办法让用户名跟hash 交叉碰撞吗，还是说密码字典里面统一加hash：hash值就行

**Comment by mortal-sec** [comment]
域名的话一般使用—gogo 参数可以指定吗

**Comment by M09Ic** [comment]
和正常的密码字典同样使用:

pwd.txt
```
hash:aad3c435b514a4eeaad3b935b51304fe
hash:aad3c435b514a4eeaad3b935b51304fe
hash:aad3c435b514a4eeaad3b935b51304fe
hash:aad3c435b514a4eeaad3b935b51304fe
hash:aad3c435b514a4eeaad3b935b51304fe
```

`zombie -U usr.txt -P pwd.txt -i smb://1.1.1.1:445`

**Comment by M09Ic** [comment]
> 域名的话一般使用—gogo 参数可以指定吗

gogo对域名的解析来自证书， 不是很推荐通过gogo获取域名信息
